name: "setup sver"
description: "setup sver"

inputs:
  version:
    description: 'sver release version'
    required: false
    default: 'v0.1.14'
  os:
    description: 'sver release os'
    required: false
    default: 'linux'
  sha256sum:
    description: 'sver sha256sum'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: cache sver
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ runner.tool_cache }}/sver
        key: ${{ runner.os }}-sver-${{ inputs.version }}-${{ inputs.os }}-amd64

    - name: install sver
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        FILE_NAME="sver_${{ inputs.version }}_${{ inputs.os }}_amd64.zip"
        FILE_URL="https://github.com/mitoma/sver/releases/download/${{ inputs.version }}/$FILE_NAME"
        mkdir -p "${{ runner.tool_cache }}/sver"
        cd "${{ runner.tool_cache }}/sver"
        curl -f -L "$FILE_URL" -o "$FILE_NAME"
        command -v sha256sum >/dev/null || sha256sum() { shasum -a 256 "$@"; }
        FILE_SHA256SUM=$(sha256sum "$FILE_NAME" | cut -f1 -d" ")
        if [[ -n "${{ inputs.sha256sum }}" && "$FILE_SHA256SUM" != "${{ inputs.sha256sum }}" ]]; then
          echo "invalid binary. expect: ${{ inputs.sha256sum }} actual: ${FILE_SHA256SUM}"
          exit 1
        fi
        unzip -o "$FILE_NAME"
        find . -type f -not \( -name sver -or -name sver.exe \) -delete

    - name: add path
      shell: bash
      run: echo "${{ runner.tool_cache }}/sver" >> "$GITHUB_PATH"
